name: Feature Branch Lint

on:
  push:
    branches:
      - 'feature/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the Node version your project needs

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run lint
      - name: Run Lint On Backend
        run: |
          cd Backend
          npm run lint

      - name: Run Lint On Frontend
        run: |
          cd Frontend/Frontend
          npm run lint

      