name: Staging Checks

on:
  pull_request:
    branches:
      - staging

  push: 
    branches:
      - staging

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint checks
        uses: uses: super-linter/super-linter@v8.2.0 
        